//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kind_farm.Conn_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;
        public Entities()
            : base("name=Entities")
        {
        }
    
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<allergens_table> allergens_table { get; set; }
        public virtual DbSet<cart_table> cart_table { get; set; }
        public virtual DbSet<kind_product_table> kind_product_table { get; set; }
        public virtual DbSet<name_product_table> name_product_table { get; set; }
        public virtual DbSet<order_manager_table> order_manager_table { get; set; }
        public virtual DbSet<orders_table> orders_table { get; set; }
        public virtual DbSet<products_table> products_table { get; set; }
        public virtual DbSet<role_table> role_table { get; set; }
        public virtual DbSet<status_table> status_table { get; set; }
        public virtual DbSet<type_product_table> type_product_table { get; set; }
        public virtual DbSet<unit_table> unit_table { get; set; }
        public virtual DbSet<users_table> users_table { get; set; }
    }
}
