//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kind_farm.Conn_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders_table()
        {
            this.cart_table = new HashSet<cart_table>();
            this.order_manager_table = new HashSet<order_manager_table>();
        }
    
        public int id_order { get; set; }
        public int id_user { get; set; }
        public int id_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_table> cart_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_manager_table> order_manager_table { get; set; }
        public virtual status_table status_table { get; set; }
        public virtual users_table users_table { get; set; }
    }
}
