//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kind_farm.Conn_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_manager_table
    {
        public int id_order_manager { get; set; }
        public int id_order { get; set; }
        public int id_product { get; set; }
    
        public virtual orders_table orders_table { get; set; }
        public virtual products_table products_table { get; set; }
    }
}
